apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    uid: "loki-datasource"
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: "tempo-datasource"
          matcherRegex: "\"trace_id\":\\s*\"([a-f0-9]+)\""
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
