apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    uid: "tempo-datasource"
    jsonData:
      tracesToLogsV2:
        datasourceUid: "loki-datasource"
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: "service"
            value: "service"
      tracesToMetrics:
        datasourceUid: "PBFA97CFB590B2093"
      lokiSearch:
        datasourceUid: "loki-datasource"
      serviceMap:
        datasourceUid: "PBFA97CFB590B2093"
